u8 string literals char8_t* are distinct from char* in C++20
Fix error C2440: 'return': cannot convert from 'const char8_t [x]' to 'const char *' when using /stdcpplatest with VS 16.6